# Generated by Django 3.1a1 on 2020-05-19 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='categories',
            field=models.CharField(choices=[('EVT', 'Eventos'), ('CUL', 'Cultos'), ('GR', 'Geral'), ('CR', 'Curiosidades'), ('PB', 'Passagens Bíblicas')], default='GR', max_length=4),
        ),
    ]
