# Generated by Django 3.1a1 on 2020-05-19 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_contato'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contato',
            old_name='mensagem',
            new_name='message',
        ),
        migrations.RenameField(
            model_name='contato',
            old_name='nome',
            new_name='name',
        ),
    ]
