# Generated by Django 3.1a1 on 2020-05-19 22:28

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_auto_20200519_1406'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='conteudo',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
