# Generated by Django 3.1a1 on 2020-05-19 22:55

import ckeditor.fields
import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0008_auto_20200519_1941'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='conteudo',
            field=ckeditor_uploader.fields.RichTextUploadingField(default=2),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='post',
            name='titulo',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
